
spring:
  application:
    name: zuul-proxy

#server:
#  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/

  server:
    eviction-interval-timer-in-ms: 1000

zuul:
  routes:
    fileuploadserver:
      path: /fileuploadserver/**
      stripPrefix: false

